= Understanding your Circulation Matrix
Lindsay Stratton <lstratton@wlsmail.org>
v1.0, 2019-12-12
:toc:

== What does the circulation matrix do?
The Circulation Matrix controls how items circulate: from which library, to which users, for how long, with how many renewals, and what fines they will generate. When an item is checked out or renewed, Evergreen scripts scan the Circulation Matrix to find the rule that best matches the item and patron being scanned.

The Circulation Matrix is created by translating library circulation policies - such as "Adult print books and audiobooks may be checked out for three weeks; if not returned by or on the due date, they will accrue overdue fines of $0.20 cents per day, to maximum of $5.00 until returned" - into codes, which are then combined into rules.

== Circulation rules
The core elements of a circulation rule are Permission Group (patron), Org Unit (library that "owns" the rule), Circulation Modifier (item type), Circulate?, Duration Rule (loan period), Recurring Fine Rule (daily fines), and Max Fine (amount at which daily fines stop accruing). All of these elements link to data that must be configured before creating a circulation rule. 

=== First steps toward a circulation rule

Map the circulation policy statement to the elements of a circulation rule: "Adult print books and audiobooks may be checked out for three weeks; if not returned by or on the due date, they will accrue overdue fines of $0.20 cents per day, to maximum of $5.00 until returned."

- Circulate -> Yes
- Print books and audiobooks -> Circulation Modifier
- Three weeks -> Loan Duration, loan duration also includes renewals (mediated or auto) 
- $0.20 fines per day -> Recurring Fine Rule
- $5.00 -> Max Fine
 
This statement could require multiple rules if "Print Books" and "Audiobooks" have their own Circulation Modifiers, if different borrowing groups have different circulation durations and/or fine rates, or if there are other special circumstances need to be met.

=== Standardization, Exceptions, Inheritance, Comprehensiveness
The most common recommendation for circulation rules is standardization. If all libraries in a consortia use the same circulation modifiers, patron groups, loan durations, and fine rates, one set of rules could be used by all libraries. Individual libraries would inherit the consortial rules.

Most consortia create standard rules for certain materials, such as books, and allow libraries to have local rules for other materials, such a A/V materials. The libraries inherit the consortial book rules, their local rules are exceptions. Other typical exception rules are used when libraries have different fine rates. 

Sometimes libraries' exception rules will have their own exceptions. For example: Consortia 1 has a standard rule for Videos, which says they circulate for 2 weeks, with fines of $0.50 per day. Library A circulates Videos for 1 week, with fines of $1.00 per day, except for employee acounts, which are not charged fines. Library A would need 2 circulation rules for Video materials.

Because it can be confusing for library staff to know or determine which rules are inherited from the consortia, and which are local exceptions, some people argue for comprehesive rules for each library, and use consortial rules only as backup in case an item or patron account is incoreectly coded. This makes communicating a specific libraries' circulation policies more transparent, and helps ensure items circulate as expected at each library; however, it also causes duplication and increases the difficulty in managing ciculation rules at the consortia level.



== Elements of a circulation rule
[%header, cols=2*]
|===
|*Field* |*Note* 
|Active |Required to enable the rule; unchecking is the only way to "delete" a rule 
|Permission Group |Required; Patron profile the rule applies to; if a rule applies to all, select "Users" 
|Org Unit |Required; CONS to apply for all libraries, otherwise specify LIB code
|Copy Circ Lib |Circ will be limited to the checkout library only
|Copy Owning Lib |Circ will be limited to materials owned by the specific library
|User Home Lib |Circ will be limited to the specific library's patrons
|Renewal? |The rule is ONLY for renewals 
|Juvenile? |The circ is limited to juvenile patron accounts; juvenile is calculated by the date of birth field and the Juvenile Age Threshold Library Setting
|Circulation Modifier |Indicates the materials the rule applies to; leave blank to apply the rule to all materials
|Copy Location |The rule will be applied only to materials within a specific library's copy location
|MARC Type |The rule applies based on the MARC 008 Type code in the bibliographic record 
|MARC Form |The rule applies based on the MARC 008 Form code in the bibliographic record  
|MARC Level |The rule applies based on the MARC 008 BLvL code in the bibliographic record 
|Videorecording Format |The rule applies based on the MARC 007, indicator 04 Videorecording Format code in the bibliographic record 
|Reference? |Only used for circulation of reference materials
|User Lower Bound |Limits circ based on user age range
|User Upper Bound |Limits circ based on user age range
|Item Age |Limits circ based on age of item
|Circulate? |Check if items circulate; uncheck for special rules when some subset of circulating materials do not circ
|Duration Rule |Required; select existing duration rule from list. If no exisiting rule, a new rule must be created before creating the circ rule
|Renewals Override |??
|Hard Date |Use if all circulated items must be returned by a set date, such as the end of a semester 
|Recurring Fine Rule |Required; select existing fine rule from list. If no existing fine rule, a new rule must be created before creating the circ rule
|Grace Override |??  
|Max Rule |Required; select existing max fine policy from list. If no existing max fine rule, a new rule must be created before creating the circ rule
|Minimum Available Copy/Hold Ratio |??
|Minimum Total Copy/Hold Ratio  |??
|Description |Recommended to explain a particular rule, particularly for exceptions to other rules 
 










