= Permission Groups
Lindsay Stratton <lstratton@wlsmail.org>
v1.0, 2019-12-12

== What are Permission Groups?
Permission Groups define different types of users and establish what tasks, functions, and features different users can access. 

=== There are two basic groups: Staff users and Patron users 

For patrons, permision groups are primarily used to define circulation rules and hold rules, and related circulation policies such as thresholds for fines, total items out, and total overdues, and limits for number of items of a specific type. They can also be used for statistical reports.

Staff groups are primarily used to manage staff client functions. Staff client functions have corresponding permissions that define what tasks can be performed. In order for a task to be completed, the permission must be assigned to the staff group who will be performing the task. For example: CHECKOUT_ITEM is the permission related to checking out items to users. That permission should be assigned to staff groups that will be responsible for circulation tasks.

== Defining Permission Groups

=== Permission group hierarchy


=== Patrons

==== Patron groups and circulation rules

=== Staff

== WLS Patron Groups

== WLS Staff Groups

== Permission groups vs. permissions assigned to users

== Permissions list, with definitions and requirements
